CREATE TABLE COURSE (
    COURSE_ID VARCHAR2(4),
    COURSE_NAME VARCHAR2(200) NOT NULL ENABLE,
    PRIMARY KEY (COURSE_ID) USING INDEX ENABLE
);

CREATE TABLE SUBJECT (
    SUBJECT_ID VARCHAR2(4) NOT NULL ENABLE,
    SUBJECT_NAME VARCHAR2(50) NOT NULL ENABLE,
    SUBJECT_MAIN VARCHAR2(4),
    CONSTRAINT SUBJECT_PK PRIMARY KEY (SUBJECT_ID) USING INDEX ENABLE
);

ALTER TABLE SUBJECT ADD CONSTRAINT SUBJECT_FK FOREIGN KEY (SUBJECT_MAIN)
    REFERENCES SUBJECT (SUBJECT_ID) ON DELETE SET NULL ENABLE;

CREATE TABLE UNIVERSITY (
    UNI_ID VARCHAR2(4),
    UNI_NAME VARCHAR2(200) NOT NULL ENABLE,
    UNI_CAMPUS VARCHAR2(200) NOT NULL ENABLE,
    PRIMARY KEY (UNI_ID) USING INDEX ENABLE
);

CREATE TABLE APPLICANT_STAT
   (YEAR VARCHAR2(4) NOT NULL ENABLE, 
	ATTENDANT NUMBER NOT NULL ENABLE, 
	FEMALE NUMBER NOT NULL ENABLE, 
	MALE NUMBER NOT NULL ENABLE, 
	NEW_APPLICANT NUMBER NOT NULL ENABLE, 
	OLD_APPLICANT NUMBER NOT NULL ENABLE, 
	CONSTRAINT APPLICANT_STAT_PK PRIMARY KEY (YEAR) USING INDEX ENABLE
);


CREATE TABLE "SUBJECT_STAT" (	
    "YEAR" VARCHAR2(4), 
	"SUBJECT_ID" VARCHAR2(4), 
	"TOTAL_SCORE" NUMBER(5,2) NOT NULL ENABLE, 
	"ATTENDANT" NUMBER(*,0) NOT NULL ENABLE, 
	"MEAN" NUMBER(5,2) NOT NULL ENABLE, 
	"SD" NUMBER(5,2) NOT NULL ENABLE, 
	"MIN" NUMBER(5,2) NOT NULL ENABLE, 
	"MAX" NUMBER(5,2) NOT NULL ENABLE, 
	"MEDIAN" NUMBER(5,2) NOT NULL ENABLE, 
	"MODE" NUMBER(5,2) NOT NULL ENABLE, 
	 CONSTRAINT "PK_SUBJECT_STAT" PRIMARY KEY ("YEAR", "SUBJECT_ID") USING INDEX  ENABLE
) ;

 ALTER TABLE "SUBJECT_STAT" ADD CONSTRAINT "FK_SUBJECT_STAT" FOREIGN KEY ("SUBJECT_ID")
	  REFERENCES "SUBJECT" ("SUBJECT_ID") ENABLE;

CREATE TABLE UNIVERSITY_STAT (
    YEAR VARCHAR2(4),
    UNI_ID VARCHAR2(4),
    COURSE_ID VARCHAR2(4),
    MIN NUMBER(5,2) NOT NULL ENABLE,
    MAX NUMBER(5,2) NOT NULL ENABLE,
    NUM_ACCEPT NUMBER(8) NOT NULL ENABLE,
    NUM_REGISTER NUMBER(8) NOT NULL ENABLE,
    NUM_PASS NUMBER(8) NOT NULL ENABLE,
    CONSTRAINT PK_UNIVERSITY_STAT PRIMARY KEY (YEAR, UNI_ID, COURSE_ID) USING INDEX ENABLE
);

ALTER TABLE UNIVERSITY_STAT ADD CONSTRAINT FK_UNIVERSITY_STAT_UNIVERSITY FOREIGN KEY (UNI_ID)
    REFERENCES UNIVERSITY (UNI_ID) ENABLE;

ALTER TABLE UNIVERSITY_STAT ADD CONSTRAINT FK_UNIVERSITY_STAT_COURSE FOREIGN KEY (COURSE_ID)
    REFERENCES COURSE (COURSE_ID) ENABLE;

CREATE TABLE STATISTIC (
    YEAR VARCHAR2(4),
    UNI_ID VARCHAR2(4),
    COURSE_ID VARCHAR2(4),
    SUBJECT_ID VARCHAR2(4),
    CONSTRAINT STATISTIC_CON_P PRIMARY KEY (YEAR, UNI_ID, COURSE_ID, SUBJECT_ID) USING INDEX ENABLE
);

ALTER TABLE STATISTIC ADD CONSTRAINT STATISTIC_CON FOREIGN KEY (YEAR, SUBJECT_ID)
    REFERENCES SUBJECT_STAT (YEAR, SUBJECT_ID) ENABLE;

ALTER TABLE STATISTIC ADD CONSTRAINT STATISTIC_CON2 FOREIGN KEY (YEAR, UNI_ID, COURSE_ID)
    REFERENCES UNIVERSITY_STAT (YEAR, UNI_ID, COURSE_ID) ENABLE;

ALTER TABLE STATISTIC ADD CONSTRAINT STATISTIC_CON3 FOREIGN KEY (YEAR)
    REFERENCES APPLICANT_STAT (YEAR) ENABLE;


