TRUNCATE TABLE APPLICANT_STAT;
TRUNCATE TABLE COURSE;
TRUNCATE TABLE STATISTIC;
TRUNCATE TABLE SUBJECT;
TRUNCATE TABLE UNIVERSITY;
TRUNCATE TABLE UNIVERSITY_STAT;
TRUNCATE TABLE SUBJECT_STAT;
TRUNCATE TABLE DEPARTMENT;
TRUNCATE TABLE FACULTY;


DROP SEQUENCE DEPARTMENT_SEQ;
DROP SEQUENCE FACULTY_SEQ;
DROP SEQUENCE COURSE_SEQ;