-- INSERT ALL DATA

-- UNIVERSITY TABLE
INSERT INTO UNIVERSITY VALUES ( 'SWU', 'มหาวิทยาลัยศรีนครินทรวิโรฒ');
INSERT INTO UNIVERSITY VALUES ( 'CU', 'จุฬาลงกรณ์มหาวิทยาลัย');

 

-- FACULTY TABLE
CREATE SEQUENCE FACULTY_SEQ 
INCREMENT BY 1 START WITH 1;

INSERT INTO FACULTY VALUES ( FACULTY_SEQ.NEXTVAL, 'วิทยาศาสตร์');
INSERT INTO FACULTY VALUES ( FACULTY_SEQ.NEXTVAL, 'สถาปัตยกรรมศาสตร์');
INSERT INTO FACULTY VALUES ( FACULTY_SEQ.NEXTVAL, 'เภสัชศาสตร์');
INSERT INTO FACULTY VALUES ( FACULTY_SEQ.NEXTVAL, 'วิศวกรรมศาสตร์');



-- DEPARTMENT TABLE
CREATE SEQUENCE DEPARTMENT_SEQ 
INCREMENT BY 1 START WITH 1;

INSERT INTO DEPARTMENT VALUES ( DEPARTMENT_SEQ.NEXTVAL, 'วิทยาการคอมพิวเตอร์');
INSERT INTO DEPARTMENT VALUES ( DEPARTMENT_SEQ.NEXTVAL, 'คณิตศาสตร์');

INSERT INTO DEPARTMENT VALUES ( DEPARTMENT_SEQ.NEXTVAL, 'ออกแบบภายใน');



-- COURSE TABLE
CREATE SEQUENCE COURSE_SEQ 
INCREMENT BY 1 START WITH 1;

INSERT INTO COURSE(COURSE_ID, DEPARTMENT_ID, FACULTY_ID) VALUES ( COURSE_SEQ.NEXTVAL, 1, 1);
INSERT INTO COURSE(COURSE_ID, DEPARTMENT_ID, FACULTY_ID) VALUES ( COURSE_SEQ.NEXTVAL, 1, 2);

INSERT INTO COURSE(COURSE_ID, DEPARTMENT_ID, FACULTY_ID) VALUES ( COURSE_SEQ.NEXTVAL, 2, 3);



-- UNIVERSITY_STAT TABLE
INSERT INTO  UNIVERSITY_STAT(YEAR, UNI_ID, COURSE_ID, MIN, MAX, NUM_ACCEPT, NUM_REGISTER, NUM_PASS) 
VALUES ( '2566', 'SWU', 1, 71.1577, 80.6828, 9, 840, 9);

INSERT INTO  UNIVERSITY_STAT(YEAR, UNI_ID, COURSE_ID, MIN, MAX, NUM_ACCEPT, NUM_REGISTER, NUM_PASS) 
VALUES ( '2565', 'SWU', 1, 71.1577, 80.6828, 9, 840, 9);

INSERT INTO  UNIVERSITY_STAT(YEAR, UNI_ID, COURSE_ID, MIN, MAX, NUM_ACCEPT, NUM_REGISTER, NUM_PASS)
VALUES ( '2566', 'SWU', 2, 49.5270, 59.9440, 32, 242, 32);



-- APPLICANT_STAT TABLE)
INSERT INTO APPLICANT_STAT(YEAR, ATTENDANT, NEW_APPLICANT, OLD_APPLICANT, FEMALE, MALE, PAPER, COMP)
VALUES ( '2567', 390950, 305513, 85437, 252207, 138743, 270567, 20184);

INSERT INTO APPLICANT_STAT(YEAR, ATTENDANT, NEW_APPLICANT, OLD_APPLICANT, FEMALE, MALE, PAPER, COMP)
VALUES ( '2566', 344547, 291661, 52886, 224917, 119630, 260267, 18590);

INSERT INTO APPLICANT_STAT(YEAR, ATTENDANT, NEW_APPLICANT, OLD_APPLICANT, FEMALE, MALE, PAPER, COMP)
VALUES ( '2565', 300730, 257482, 43249, 201804, 98701, 300730, 0);



-- SUBJECT TABLE
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT', 'การทดสอบวิชาความถนัดทางวิชาการและวิชาชีพ', NULL);
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT1', 'ความถนัดทางคณิตศาสตร์', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT2', 'ความถนัดทางวิทยาศาสตร์', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT3', 'ความถนัดทางวิศวกรรมศาสตร์', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT4', 'ความถนัดทางสถาปัตยกรรมศาสตร์', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT5', 'ความถนัดทางวิชาชีพครู', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT6', 'ความถนัดทางศิลปกรรมศาสตร์', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7', 'ความถนัดทางภาษาต่างประเทศ', 'PAT');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.1', 'ความถนัดทางภาษาฝรั่งเศส', 'PAT7');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.2', 'ความถนัดทางภาษาเยอรมัน', 'PAT7');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.3', 'ความถนัดทางภาษาญี่ปุ่น', 'PAT7');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.4', 'ความถนัดทางภาษาจีน', 'PAT7');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.5', 'ความถนัดทางภาษาอาหรับ', 'PAT7');
INSERT INTO SUBJECT (SUBJECT_ID, SUBJECT_NAME, SUBJECT_MAIN) VALUES ( 'PAT7.6', 'ความถนัดทางภาษาบาลี', 'PAT7');



-- SUBJECT_STAT TABLE
INSERT INTO SUBJECT_STAT ("YEAR", SUBJECT_ID, TOTAL_SCORE, ATTENDANT, FEMALE, MALE, NEW_APPLICANT, OLD_APPLICANT, MEAN, SD, "MIN", "MAX", "MEDIAN", "MODE")
VALUES ('2565', 'PAT1', 300, 21319, NULL, NULL, NULL, NULL, 61.140, 35.304, 0.000, 300.000, 54.000, 42.000);



-- STATISTIC TABLE
INSERT INTO  STATISTIC ( YEAR, UNI_ID, COURSE_ID, SUBJECT_ID ) VALUES ('2565', 'SWU', 1, 'PAT1');